version: 2

project_name: qo

builds:
  - binary: qo
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/kiki-ki/go-qo/cmd.version={{.Version}}
    main: ./cmd/qo

archives:
  - formats:
      - tar.gz
    files:
      - LICENSE
      - README.md

# deprecated brews in goreleaser.
# ref: https://goreleaser.com/deprecations/#brews
brews:
  - repository:
      owner: kiki-ki
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/kiki-ki/go-qo
    description: "Query JSON data with SQL"
    install: |
      bin.install "qo"

changelog:
  sort: asc
  groups:
    - title: "Features"
      regexp: '^feat(\(.+\))?:'
      order: 0
    - title: "Bug Fixes"
      regexp: '^fix(\(.+\))?:'
      order: 1
  filters:
    exclude:
      - '^chore(\(.+\))?:'
